package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	goclawConfig "github.com/smallnest/goclaw/config"
	"github.com/smallnest/goclaw/console/internal/model"
	"github.com/smallnest/goclaw/console/internal/service"
)

// AgentHandler handles agent API endpoints
type AgentHandler struct {
	config     *goclawConfig.Config
	configPath string
	agentSvc   *service.AgentService
}

// NewAgentHandler creates a new agent handler
func NewAgentHandler(cfg *goclawConfig.Config, configPath string) *AgentHandler {
	return &AgentHandler{
		config:     cfg,
		configPath: configPath,
	}
}

// SetAgentService sets the agent service (called after initialization)
func (h *AgentHandler) SetAgentService(svc *service.AgentService) {
	h.agentSvc = svc
}

// HandleStatus handles GET /api/agent and GET /api/agent/
func (h *AgentHandler) HandleStatus(c *gin.Context) {
	if h.agentSvc != nil {
		c.JSON(http.StatusOK, h.agentSvc.GetStatus())
		return
	}

	c.JSON(http.StatusOK, model.AgentStatus{
		Status:  "running",
		Message: "Agent service is available",
	})
}

// HandleHealth handles GET /api/agent/health
func (h *AgentHandler) HandleHealth(c *gin.Context) {
	if h.agentSvc != nil {
		c.JSON(http.StatusOK, h.agentSvc.GetHealth())
		return
	}

	c.JSON(http.StatusOK, model.AgentHealth{
		Status:    "healthy",
		Timestamp: time.Now(),
	})
}

// HandleProcess handles POST /api/agent/process
// Supports both streaming (SSE) and non-streaming responses
func (h *AgentHandler) HandleProcess(c *gin.Context) {
	var req model.AgentProcessRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, model.ErrorResponse{Error: err.Error()})
		return
	}

	// Use AgentService if available
	if h.agentSvc != nil {
		ctx := c.Request.Context()

		// Check if streaming is requested
		if req.Stream {
			h.handleProcessStream(c, ctx, &req)
			return
		}

		// Non-streaming response
		ctx, cancel := context.WithTimeout(ctx, 60*time.Second)
		defer cancel()

		response, err := h.agentSvc.ProcessMessage(ctx, &req)
		if err != nil {
			c.JSON(http.StatusInternalServerError, model.ErrorResponse{Error: err.Error()})
			return
		}
		c.JSON(http.StatusOK, response)
		return
	}

	// Fallback: Return session info when agent service is not initialized
	response := model.AgentProcessResponse{
		SessionID: req.SessionID,
		Output: map[string]interface{}{
			"message": "Agent service not initialized. Please check configuration.",
			"input":   req.Input,
			"model":   h.config.Agents.Defaults.Model,
			"status":  "error",
			"note":    "AgentService requires initialization with valid provider configuration",
		},
		Status: "error",
	}

	c.JSON(http.StatusOK, response)
}

// handleProcessStream handles streaming SSE response
func (h *AgentHandler) handleProcessStream(c *gin.Context, ctx context.Context, req *model.AgentProcessRequest) {
	// Set SSE headers with UTF-8 charset
	c.Header("Content-Type", "text/event-stream; charset=utf-8")
	c.Header("Cache-Control", "no-cache")
	c.Header("Connection", "keep-alive")
	c.Header("X-Accel-Buffering", "no") // Disable nginx buffering

	// Ensure headers are sent immediately
	c.Writer.WriteHeader(http.StatusOK)

	// Get flusher
	flusher, ok := c.Writer.(http.Flusher)
	if !ok {
		c.JSON(http.StatusInternalServerError, model.ErrorResponse{Error: "streaming not supported"})
		return
	}

	// Get event channel - all events including init and done are generated by agent_service
	eventChan, err := h.agentSvc.ProcessMessageStream(ctx, req)
	if err != nil {
		// Send error event
		errorEvent := model.AgentEvent{
			Object: "response",
			ID:     "error",
			Status: "failed",
			Error: &model.AgentError{
				Type:    "stream_error",
				Message: err.Error(),
			},
			Timestamp: time.Now().UnixMilli(),
		}
		data, _ := json.Marshal(errorEvent)
		c.Writer.Write([]byte(fmt.Sprintf("data: %s\n\n", data)))
		flusher.Flush()
		return
	}

	// Stream events - all events now include sequence_number from agent_service
	for event := range eventChan {
		// Convert event to JSON
		data, err := json.Marshal(event)
		if err != nil {
			continue
		}

		// Write SSE event with proper format
		c.Writer.Write([]byte(fmt.Sprintf("data: %s\n\n", data)))
		flusher.Flush()
	}
}

// HandleAdminStatus handles GET /api/agent/admin/status
func (h *AgentHandler) HandleAdminStatus(c *gin.Context) {
	if h.agentSvc != nil {
		c.JSON(http.StatusOK, h.agentSvc.GetAdminStatus())
		return
	}

	c.JSON(http.StatusOK, model.AgentAdminStatus{
		Active:    false,
		SessionID: "",
		Status:    "idle",
		StartTime: nil,
		Progress:  0,
	})
}

// HandleShutdown handles POST /api/agent/shutdown
func (h *AgentHandler) HandleShutdown(c *gin.Context) {
	if h.agentSvc != nil {
		if err := h.agentSvc.Shutdown(); err != nil {
			c.JSON(http.StatusInternalServerError, model.ErrorResponse{Error: err.Error()})
			return
		}
	}
	c.Status(http.StatusNoContent)
}

// HandleAdminShutdown handles POST /api/agent/admin/shutdown
func (h *AgentHandler) HandleAdminShutdown(c *gin.Context) {
	if h.agentSvc != nil {
		h.agentSvc.StopAdminSession()
	}
	c.Status(http.StatusNoContent)
}

// HandleGetRunningConfig handles GET /api/agent/running-config
func (h *AgentHandler) HandleGetRunningConfig(c *gin.Context) {
	if h.agentSvc != nil {
		c.JSON(http.StatusOK, h.agentSvc.GetRunningConfig())
		return
	}

	if h.config == nil {
		c.JSON(http.StatusOK, model.AgentRunningConfig{
			MaxIters:       15,
			MaxInputLength: 4000,
		})
		return
	}

	c.JSON(http.StatusOK, model.AgentRunningConfig{
		MaxIters:       h.config.Agents.Defaults.MaxIterations,
		MaxInputLength: 4000, // Default value
	})
}

// HandleUpdateRunningConfig handles PUT /api/agent/running-config
func (h *AgentHandler) HandleUpdateRunningConfig(c *gin.Context) {
	var req model.AgentRunningConfig
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, model.ErrorResponse{Error: err.Error()})
		return
	}

	// Use AgentService if available
	if h.agentSvc != nil {
		if err := h.agentSvc.UpdateRunningConfig(&req, h.configPath); err != nil {
			c.JSON(http.StatusInternalServerError, model.ErrorResponse{Error: err.Error()})
			return
		}
		c.JSON(http.StatusOK, req)
		return
	}

	// Fallback: Update config directly
	if h.config != nil {
		h.config.Agents.Defaults.MaxIterations = req.MaxIters

		// Save config
		if h.configPath != "" {
			goclawConfig.Save(h.config, h.configPath)
		}
	}

	c.JSON(http.StatusOK, req)
}

// HandleGetTools handles GET /api/agent/tools
func (h *AgentHandler) HandleGetTools(c *gin.Context) {
	if h.agentSvc != nil {
		tools, err := h.agentSvc.GetToolsInfo()
		if err != nil {
			c.JSON(http.StatusInternalServerError, model.ErrorResponse{Error: err.Error()})
			return
		}
		c.JSON(http.StatusOK, tools)
		return
	}

	c.JSON(http.StatusOK, map[string]interface{}{})
}
